version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/editors/vscode"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(vscode)"
    labels:
      - "dependencies"
      - "vscode"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci"
    labels:
      - "ci"
    open-pull-requests-limit: 5
